name: Build & Deploy (Frontend, Docker, self-hosted)

on:
  push:
    branches: [develop, master]

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/admin-frontend

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Select env file for build
        run: |
          if [ "${GITHUB_REF##*/}" = "develop" ]; then cp .env.test .env; else cp .env.prod .env; fi
          ls -l .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Enable corepack
        run: corepack enable

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Build & Push image (tag by branch)
        run: |
          if [ "${GITHUB_REF##*/}" = "develop" ]; then TAG=test; else TAG=prod; fi
          docker build -t $IMAGE:$TAG -t $IMAGE:${GITHUB_SHA} .
          docker push $IMAGE:$TAG
          docker push $IMAGE:${GITHUB_SHA}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR (pull needs auth)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Ensure network
        run: docker network create qrinn_net || true

      - name: Compose up (only current env)
        working-directory: ${{ github.workspace }}/deploy
        run: |
          if [ "${GITHUB_REF##*/}" = "develop" ]; then SVC=admin-fe-test; else SVC=admin-fe-prod; fi
          docker compose pull $SVC || true
          docker compose up -d $SVC
          docker system prune -f
      
      - name: Publish Nginx vhost & reload edge
        run: |
          sudo mkdir -p /srv/qr-inn/nginx-dynamic
          sudo cp ${{ github.workspace }}/deploy/nginx/conf.d/admin.conf /srv/qr-inn/nginx-dynamic/admin.conf
          docker exec -it qrinn-nginx nginx -t
          docker exec qrinn-nginx nginx -s reload

